### ISSUE TITLE
runtime error when filtering by 1d query window

### ISSUE THREAD

**Issue by donwany** [kubecost/kubectl-cost#123]
![Screen Shot 2022-07-06 at 2 59 52 PM](https://user-images.githubusercontent.com/10055091/177632993-7a875899-82e9-4321-9ee2-d4cfc1768a83.png)

gz#2118<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2118'>Zendesk ticket #2118</a>)</i>

**Comment by zorrobyte** [comment]
@donwany Could you share your provider, the version you are running, and more information on how you are querying?

**Comment by nealormsbee** [comment]
Temporarily co-assigning to @michaelmdresser because he's the primary author of this project, and also to myself and @zorrobyte as engineer on support rotation and first responder.

**Comment by michaelmdresser** [comment]
Hi @donwany, I've just released v0.2.12 of kubectl-cost, which should prevent this panic. The TUI may still encounter an error for you because I'm not sure what the root-cause issue is, but we'll have a workable error message starting in v0.2.12 rather than just a panic.

Thanks for your patience with this issue. When you get a chance, would you upgrade to v0.2.12 and let me know what error behavior you encounter in the TUI?

**Comment by michaelmdresser** [comment]
I'm going to close this issue as completed because we have a presumed fix that has been out for a little while. If you're still encountering a problem, please feel free to open a new issue or reopen this one!
